name: Pluto benchmark compile times

on:
    workflow_dispatch:
    push:
        paths-ignore:
            - "frontend/**"
            - "frontend-bundler/**"
            - "frontend-dist/**"
            - "test/frontend/**"
            - "**.md"
        branches:
            - main
    pull_request:
        paths-ignore:
            - "frontend/**"
            - "frontend-bundler/**"
            - "frontend-dist/**"
            - "test/frontend/**"
            - "**.md"
        branches-ignore:
            - release

jobs:
    benchmark-compile-times:
        runs-on: "ubuntu-latest"
        timeout-minutes: 30

        steps:
            - uses: actions/checkout@v2
            - uses: julia-actions/setup-julia@v1
            - uses: julia-actions/cache@v1
            - uses: julia-actions/julia-buildpkg@v1
            - name: Benchmark without precompile directives
              run: julia perf/compiletimes.jl
              env:
                PLUTO_COMPILE_TIMES_MODE: "without_precompile_directives"
            - name: Benchmark with precompile directives
              run: julia perf/compiletimes.jl

