name: Fire release triggers

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        repository: ['fonsp/pluto-on-binder', 'JuliaPluto/sample-notebook-previews']
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl \
            -X POST \
            -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ matrix.repository }}/dispatches \
            -d '{"event_type":"release_pluto"}'
