name: Run Julia Nightly tests

# Controls when the action will run.
on:
    push:
        paths-ignore: "frontend/**"
    pull_request:
        paths-ignore: "frontend/**"
    schedule:
        # every monday
        - cron: "0 0 * * 1"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "test-nightly"
    test-nightly:
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        continue-on-error: true
        strategy:
            matrix:
                julia-version: ["nightly"]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.julia-version }}
            - uses: julia-actions/julia-runtest@v0.1
